### ISSUE TITLE
Sheet sheet is out of date :(

### ISSUE THREAD

**Issue by laura-dietz** [damontallen/IPython-quick-ref-sheets#2]
$ ipython notebook --pylab inline
[E 10:04:59.311 NotebookApp] Support for specifying --pylab on the command line has been removed.
[E 10:04:59.311 NotebookApp] Please use `%pylab inline` or `%matplotlib inline` in the notebook itself.
$

**Comment by damontallen** [comment]
@laura-dietz  Thank you for letting me know. 
Updated Quickref sheet.
